language: python

python:
  - "3.6"

branches:
  only:
    - master
    
install:
  - pip install -r requirements.txt

before_script:
  - chmod +x pytest.py
  
script:
  - python pytest.py `git diff --name-only HEAD^ --diff-filter=d | grep ".doc"`
  
notifications:
  email:
    recipients:
      - v.shevchenko@student.csn.khai.edu
    on_success: always
    on_failure: change